const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function test() {
  const base = 'https://flash-buk-01.s3.ap-south-1.amazonaws.com/ScratchGardImages/Uploads/Owner/Catalog/';
  const brandImages = {
    "GoPro": "GoPro.jpg",
    "BlackBerry": "blackberry.png",
    "InFocus": "Infocus.jpg",
    "Ford": "FORD.jpg",
    "DELL": "DELL.jpg",
    "Realme": "Realme.jpg",
    "Xiaomi": "Xiaomi.jpg",
    "Tecno": "Tecno.jpg",
    "Zavia": "Zavia.png",
    "Jio": "Jio.jpg",
    "Samsung": "Samsung.jpg",
    "Canon": "Canon.jpg",
    "Fitbit": "Fitbit.jpg",
    "Google": "Google.jpg",
    "CoolPad": "coolpad.jpg",
    "ORAIMO": "oraimo.jpg",
    "GLO": "glo.jpg",
    "Oppo": "Oppo.jpg",
    "LG": "LG.jpg",
    "Crossbeat": "Crossbeat.png",
    "Nikon": "Nikon.jpg",
    "Fire Boltt": "Fire Boltt.jpg",
    "Lenovo": "Lenovo.jpg",
    "IQOS": "IQOS.jpg",
    "Bose": "Bose.jpg",
    "Nokia": "Nokia.jpg",
    "Skullcandy": "Skullcandy.jpg",
    "Noise": "Noise.jpg",
    "Huawei": "Huawei.jpg",
    "Itel": "Itel.jpg",
    "Dimensions Testing": "Dimensions Testing.jpg",
    "Vivo": "vivo.jpg",
    "AmazFit": "Amazfit.jpg",
    "LeEco": "LeEco.jpg",
    "Infinix": "Infinix.jpg",
    "Sony": "Sony.jpg",
    "Honda": "HONDA.jpg",
    "Urban": "Urban.jpg",
    "Lava": "Lava.jpg",
    "Micromax": "Micromax.jpg",
    "BOAT": "Boat.jpg",
    "Motorola": "Motorola.jpg",
    "Gizmore": "Gizmore.jpg",
    "Garmin": "Garmin.jpg",
    "Dizo": "Dizo.jpg",
    "Gionee": "Gionee.jpg",
    "HTC": "Htc.jpg",
    "Panasonic": "Panasonic.jpg",
    "Maxima": "Maxima.png",
    "OnePlus": "Oneplus.jpg",
    "Mafe": "Mafe.jpg",
    "Pebble": "Pebble.jpg",
    "PLAY": "PLAY.png",
    "Meizu": "MEIZU.jpg",
    "Foxin": "Foxin.png",
    "Molife": "Molife.png",
    "Macbook": "MACBOOK.jpg",
    "ZTE": "ZTE.jpg",
    "Fastrack": "Fastrack.png",
    "DJI": "DJI.png",
    "Honor": "Honor.jpg",
    "Portronics": "Portronics.png",
    "Hyundai": "HYUNDAI.jpg",
    "Apple": "APPLE.jpg",
    "Jeep": "JEEP.jpg",
    "Toyota": "TOYOTA.jpg",
    "KIA": "KIA.jpg",
    "Mahindra": "MAHINDRA.jpg",
    "Nissan": "NISSAN.jpg",
    "MG": "MG.jpg",
    "Volkswagen": "volkswagen.jpg",
    "Tata": "TATA.jpg",
    "Comio": "COMIO.jpg",
    "Moto": "Moto.png",
    "Yu": "YU.jpg",
    "HP": "HP.jpg",
    "MicroSoft": "Microsoft.jpg",
    "Asus": "Asus.png",
    "VERTU": "VERTU.jpg",
    "MuvAudio": "MuvAudio.jpg",
    "Ubon": "Ubon.jpg",
    "Vibez": "Vibez.jpg",
    "CORUM": "CORUM.jpg",
    "Intex": "Intex.jpg",
    "Syska": "Syska.png",
    "Minix": "MINIX.jpg",
    "Benco": "Benco.jpg",
    "TAGG": "TAGG.jpg",
    "pTron": "PTRON.jpg",
    "GOQii": "GOQii.jpg",
    "Xolo": "Xolo.jpg",
    "iBall": "iball.png",
    "Boult": "Boult.png",
    "OG": "OG.png",
    "U&i": "U&i.png",
    "REALIX": "REALIX.jpg",
    "Kratos": "Kratos.jpg",
    "Mobilla": "Mobilla.jpg",
    "Corseca": "Corseca.jpg",
    "Rapz": "Rapz.jpg",
    "Ather": "ather.jpg",
    "Honeybud": "honeybud.jpg",
    "Unix": "Unix.jpg",
    "Helix Timex": "Helix Timex.jpg",
    "Timex": "Timex.jpg",
    "Hammer": "Hammer.jpg",
    "FLiX": "FLiX.jpg",
    "TCL": "TCL.jpg",
    "Diesel": "DIESEL.jpg",
    "Palm": "Palm.jpg",
    "LYF": "LYF.jpg",
    "Soyes": "Soyes.jpg",
    "Kindle": "Kindle.jpg",
    "TVS": "TVS.jpg",
    "FUJITSU": "FUJITSU.jpg",
    "I KALL": "I KALL.jpg",
    "TRES CARE": "TRES CARE.jpg",
    "Nothing": "Nothing.jpg",
    "Acer": "Acer.jpg",
    "Suzuki": "SUZUKI.jpg"
  };

  let updated = 0;
  for (const [name, img] of Object.entries(brandImages)) {
    const res = await prisma.brand.updateMany({
      where: { name: { equals: name, mode: 'insensitive' } },
      data: { imageUrl: img }
    });
    updated += res.count;
  }
  console.log(`Updated ${updated} brands with exact S3 images in DB!`);
}

test().catch(console.error).finally(() => prisma.$disconnect());
